server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechart_program1?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapper/*.xml