server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phoneinfo?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    date-format: yyyy-MM-dd
    view:
      suffix: .jsp
      prefix: /WEB-INF/page/
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:/mapper/*.xml