server:
  port: 80
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springbootcd?serverTimezone=GMT%2B8
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: pageNum=currentPage,pageSize=pageSize
logging:
  level.com.springboot.thymeleaf.dao: debug