spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootcd?serverTimezone=%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  servlet:
    context-path: /
  port: 80